### PR TITLE
1.0: fixed printf type position

### PR DESCRIPTION
**Pull request by zvezdochiot**
1.0:
* fixed printf type position
* move code to src

https://github.com/FS-make-simple/bluedelta/releases/tag/1.0

### CODE REVIEW

**Comment by iblue** [comment]
Hi and thanks for the PR. 

A cast to `long int` is not required, as the variables are already declared as `uint64_t`. Moving the code to `src/` is a matter of taste and also does not improve the software.

I'm sorry, but I will not merge that.

**Comment by zvezdochiot** [comment]
@iblue say:
>A cast to long int is not required, as the variables are already declared as uint64_t.

Win10. GCC 10.1.0.
```make
gcc -std=c11 -Wall -Werror -ggdb -I./include -I. -c utils/diff.c -o utils/diff.o
utils/diff.c: In function 'diff':
utils/diff.c:57:57: error: format '%ld' expects argument of type 'long int', but argument 2 has type 'uint64_t' {aka 'long long unsigned int'} [-Werror=format=]
   57 |         printf("  DEBUG: Found difference at position %ld\n", position);
```

**Comment by iblue** [comment]
I see. Please check the latest changes (d14fe62c0da224496c8aea2b3183f6c0e8cf2e55), does it work on your machine now?

**Comment by zvezdochiot** [comment]
@iblue say:
>Please check the latest changes (d14fe62), does it work on your machine now?

`ftell` return `long int`:

```make
$ make
gcc -std=c11 -Wall -Werror -O3 -I./include -I. -c utils/diff.c -o utils/diff.o
utils/diff.c: In function 'diff':
utils/diff.c:75:10: error: format '%I64u' expects argument of type 'long long unsigned int', but argument 2 has type 'long int' [-Werror=format=]
   75 |   printf("    FILE1 (input):  %" PRIu64 "\n", ftell(file1));
      |          ^~~~~~~~~~~~~~~~~~~~~~~              ~~~~~~~~~~~~
      |                                               |
      |                                               long int
```

**Comment by iblue** [comment]
The issue is, that on your system, `ftell`/`fseek` do not return 64 bit integers. However, this is required, as otherwise the tool would break on files larger than 4 GB. I replaced them by their POSIX compliant alternatives `fseeko`/`ftello`. Please try again.

However, I'm not sure if that will work on Windows. Maybe you have to use `_fseeki64`/`_ftelli64`. I you want, please patch accordingly and send a pull request, I will review it then. Thanks for your efforts!

**Comment by zvezdochiot** [comment]
```sh
$ make
gcc -std=c11 -Wall -Werror -O3 -I./include -I. -c utils/diff.c -o utils/diff.o
gcc -std=c11 -Wall -Werror -O3 -I./include -I. -c utils/patch.c -o utils/patch.o
gcc -std=c11 -Wall -Werror -O3 -I./include -I. -c main.c -o main.o
gcc -std=c11 -Wall -Werror -O3 -o bluedelta ./utils/diff.o ./utils/patch.o main.o
```
```sh
$ ./bluedelta diff.o patch.o bdiff.o
```
```sh
$ ls -l
total 157
-rw-r--r-- 1 HP 197121   4385 янв 25 19:15 bdiff.o
-rwxr-xr-x 1 HP 197121 122073 янв 25 19:14 bluedelta.exe*
-rw-r--r-- 1 HP 197121   3053 янв 25 19:14 diff.o
-rw-r--r-- 1 HP 197121   4249 янв 25 19:14 patch.o
```
Good!

**Pull request closed without merging**
